apiVersion:
  v1
kind:
  PersistentVolumeClaim
metadata:
  name:
    robo-rlhf-data-pvc
  namespace:
    robo-rlhf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:
        50Gi
  storageClassName:
    fast-ssd
